language: php
sudo: false

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
    fast_finish: true

cache:
    directories:
        - ./vendor

install:
    - composer self-update
    - composer install

script:
    - [[ "$TRAVIS_PHP_VERSION" != "7.0" ]] || ./vendor/bin/codecept run
    - [[ "$TRAVIS_PHP_VERSION" == "7.0" ]] && ./vendor/bin/codecept run --coverage-xml

after_script:
    - [[ "$TRAVIS_PHP_VERSION" == "7.0" ]] && ./vendor/bin/coveralls
