language: php
sudo: false

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
    fast_finish: true

cache:
    directories:
        - ./vendor

install:
    - composer self-update
    - composer install

script:
    - if [ "${TRAVIS_PHP_VERSION}" != "7.0" ]; then ./vendor/bin/codecept run; fi;
    - if [ "${TRAVIS_PHP_VERSION}" == "7.0" ]; then ./vendor/bin/codecept run --coverage-xml; fi;

after_script:
    - if [ "${TRAVIS_PHP_VERSION}" == "7.0" ]; then ./vendor/bin/coveralls; fi;
