language: php
sudo: false

# PHP 5.4 and 5.5 are supported on a best-effort basis and are intentionally
# not included in the tested versions here, as the dependencies for the testing
# tools require newer versions of PHP.
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
    fast_finish: true
    allow_failure:
        - php: nightly

cache:
    directories:
        - ./vendor

install:
    - composer self-update
    - composer install

script:
    - if [ "${TRAVIS_PHP_VERSION}" != "7.0" ]; then ./vendor/bin/codecept run; fi;
    - if [ "${TRAVIS_PHP_VERSION}" == "7.0" ]; then ./vendor/bin/codecept run --coverage-xml; fi;

after_script:
    - if [ "${TRAVIS_PHP_VERSION}" == "7.0" ]; then ./vendor/bin/coveralls; fi;
